### ISSUE TITLE
Output not rendering

### ISSUE THREAD

**Issue by kasperjay** [Mirage-Mode/SpleetSpace#2]
The program installed successfully and appears to function as intended, except no files are being created... I've tried using a different song, outputting to a different folder, and changing the number of stems to no avail.  No error thrown; on the contrary, the result box at the bottom of the window states the splitting completed and saved successfully  :/

**Comment by emirsahin1** [comment]
Hi! Thanks for reaching out about your issue Kasper. 

How long does it take for it to finish splitting? If it says "Split Complete" within a couple of seconds, then the splitting process is most likely failing and the error is not being caught. 

Just in case it's a permission issue, could you also try using the youtube downloader to see if that has any issues saving?

Let us know and we'll try to pinpoint what the issue may be.

**Comment by emirsahin1** [comment]
Closed due to lack of information.
